# Stochastic Invalidation & Risk Architecture
# Black Box risk engine for distressed-asset recovery modeling.

#' Generate synthetic distressed-asset data that works without API calls.
#'
#' @param n_assets Integer number of assets to model.
#' @param seed Integer RNG seed for reproducibility.
#' @return data.frame with local synthetic portfolio data.
generate_synthetic_portfolio <- function(n_assets = 100, seed = 42) {
  set.seed(seed)

  data.frame(
    asset_id = sprintf("AST-%03d", seq_len(n_assets)),
    exposure = round(runif(n_assets, min = 1.5e6, max = 1.2e7), 0),
    base_recovery = pmin(
      pmax(rnorm(n_assets, mean = 1.25, sd = 0.22), 0.55),
      1.9
    ),
    cost_of_capital = pmin(
      pmax(rnorm(n_assets, mean = 0.95, sd = 0.14), 0.60),
      1.60
    ),
    exit_days = as.integer(runif(n_assets, min = 60, max = 210)),
    stringsAsFactors = FALSE
  )
}

#' Internal scenario dispatcher.
#'
#' @param portfolio data.frame generated by generate_synthetic_portfolio.
#' @param scenario_name One of: baseline, rate_shock, liquidity_trap, variance_error, black_swan.
#' @param seed Integer seed to keep scenario sampling deterministic.
#' @return portfolio with stressed recovery estimates.
apply_scenario <- function(portfolio, scenario_name, seed = 42) {
  set.seed(seed)
  p <- portfolio

  if (scenario_name == "baseline") {
    p$scenario_recovery <- p$base_recovery + rnorm(nrow(p), mean = 0, sd = 0.04)
    p$scenario_exit_days <- p$exit_days
    p$scenario_cost_of_capital <- p$cost_of_capital
  }

  if (scenario_name == "rate_shock") {
    rate_jump <- runif(nrow(p), min = 0.02, max = 0.03) # 200-300 bps shock
    p$scenario_cost_of_capital <- p$cost_of_capital + rate_jump
    p$scenario_recovery <- p$base_recovery - (rate_jump * 4.6) + rnorm(nrow(p), 0, 0.05)
    p$scenario_exit_days <- p$exit_days + as.integer(runif(nrow(p), 20, 60))
  }

  if (scenario_name == "liquidity_trap") {
    p$scenario_exit_days <- as.integer(runif(nrow(p), min = 180, max = 450))
    horizon_penalty <- (p$scenario_exit_days - p$exit_days) / 1000
    p$scenario_recovery <- p$base_recovery - horizon_penalty + rnorm(nrow(p), 0, 0.03)
    p$scenario_cost_of_capital <- p$cost_of_capital + horizon_penalty / 2
  }

  if (scenario_name == "variance_error") {
    volatility_error <- runif(nrow(p), min = 0.15, max = 0.20)
    directional_error <- sample(c(-1, 1), nrow(p), replace = TRUE)
    p$scenario_recovery <- p$base_recovery + directional_error * volatility_error
    p$scenario_exit_days <- p$exit_days + as.integer(runif(nrow(p), -15, 30))
    p$scenario_cost_of_capital <- p$cost_of_capital + runif(nrow(p), 0.01, 0.05)
  }

  if (scenario_name == "black_swan") {
    rate_jump <- runif(nrow(p), min = 0.02, max = 0.04)
    p$scenario_exit_days <- as.integer(runif(nrow(p), min = 220, max = 500))
    tail_loss <- rbeta(nrow(p), shape1 = 2, shape2 = 8)
    p$scenario_cost_of_capital <- p$cost_of_capital + rate_jump + 0.07
    p$scenario_recovery <- p$base_recovery - 0.25 - tail_loss - rate_jump * 4.5 + rnorm(nrow(p), 0, 0.06)
  }

  p$scenario_recovery <- pmax(p$scenario_recovery, 0)
  p$scenario_name <- scenario_name

  p
}

#' Black Box risk engine for stochastic invalidation.
#'
#' @param portfolio Optional local data.frame. If NULL, synthetic data is auto-generated.
#' @param scenario_weights Named numeric vector of risk weights.
#' @param seed Integer for deterministic simulation.
#' @return List with detailed results, scenario summary, and optional ggplot object.
black_box_risk_engine <- function(
  portfolio = NULL,
  scenario_weights = c(
    baseline = 0.10,
    rate_shock = 0.20,
    liquidity_trap = 0.20,
    variance_error = 0.20,
    black_swan = 0.30
  ),
  seed = 42
) {
  if (is.null(portfolio)) {
    portfolio <- generate_synthetic_portfolio(seed = seed)
  }

  required_cols <- c("asset_id", "exposure", "base_recovery", "cost_of_capital", "exit_days")
  missing_cols <- setdiff(required_cols, names(portfolio))
  if (length(missing_cols) > 0) {
    stop(sprintf("Portfolio missing required columns: %s", paste(missing_cols, collapse = ", ")))
  }

  scenarios <- c("baseline", "rate_shock", "liquidity_trap", "variance_error", "black_swan")
  scenario_runs <- lapply(seq_along(scenarios), function(i) {
    apply_scenario(portfolio, scenarios[i], seed = seed + i)
  })
  all_results <- do.call(rbind, scenario_runs)

  all_results$z_score <- as.numeric(scale(all_results$scenario_recovery))
  all_results$institutional_range <- 1.0
  all_results$invalidation_point <- all_results$scenario_cost_of_capital > all_results$scenario_recovery
  all_results$ruin_threshold <- all_results$scenario_recovery < all_results$institutional_range
  all_results$high_risk_alert <- all_results$z_score < -2 | all_results$invalidation_point

  summary_table <- aggregate(
    cbind(
      scenario_recovery,
      scenario_cost_of_capital,
      scenario_exit_days,
      exposure,
      invalidation_point,
      ruin_threshold,
      high_risk_alert
    ) ~ scenario_name,
    data = all_results,
    FUN = mean
  )

  sd_by_scenario <- aggregate(
    scenario_recovery ~ scenario_name,
    data = all_results,
    FUN = sd
  )
  names(sd_by_scenario)[2] <- "recovery_sd"

  summary_table <- merge(summary_table, sd_by_scenario, by = "scenario_name", sort = FALSE)
  names(summary_table)[names(summary_table) == "scenario_recovery"] <- "mean_recovery"
  names(summary_table)[names(summary_table) == "scenario_cost_of_capital"] <- "mean_cost_of_capital"
  names(summary_table)[names(summary_table) == "scenario_exit_days"] <- "mean_exit_days"
  names(summary_table)[names(summary_table) == "invalidation_point"] <- "invalidation_ratio"
  names(summary_table)[names(summary_table) == "ruin_threshold"] <- "ruin_ratio"
  names(summary_table)[names(summary_table) == "high_risk_alert"] <- "high_risk_ratio"

  summary_table$risk_weight <- scenario_weights[summary_table$scenario_name]
  summary_table$stress_impact <- pmax(0, (1 - summary_table$mean_recovery) + summary_table$invalidation_ratio)
  summary_table$weighted_risk_stress_score <- summary_table$stress_impact * summary_table$risk_weight

  plot_obj <- NULL
  if (requireNamespace("ggplot2", quietly = TRUE)) {
    plot_obj <- ggplot2::ggplot(summary_table, ggplot2::aes(x = scenario_name, y = mean_recovery, fill = scenario_name)) +
      ggplot2::geom_col(width = 0.75, alpha = 0.85, show.legend = FALSE) +
      ggplot2::geom_hline(yintercept = 1.0, linetype = "dashed", color = "#D32F2F") +
      ggplot2::labs(
        title = "Black Box Recovery Outcomes by Stress Scenario",
        subtitle = "Dashed line = Institutional Range (1.0)",
        x = "Scenario",
        y = "Mean Recovery"
      ) +
      ggplot2::theme_minimal(base_size = 11)
  }

  list(
    engine_name = "Black Box Risk Engine",
    scenarios = summary_table,
    detailed_results = all_results,
    portfolio_size = nrow(portfolio),
    weighted_portfolio_risk_stress_score = sum(summary_table$weighted_risk_stress_score),
    plot = plot_obj
  )
}

#' Helper to print an institutional summary.
#' @param engine_result list returned from black_box_risk_engine().
#' @return invisibly returns input result.
print_institutional_summary <- function(engine_result) {
  cat("=== Black Box Risk Engine Summary ===\n")
  cat(sprintf("Portfolio Size: %d assets\n", engine_result$portfolio_size))
  cat(sprintf("Weighted Portfolio Risk/Stress Score: %.4f\n\n", engine_result$weighted_portfolio_risk_stress_score))
  print(engine_result$scenarios)

  invisible(engine_result)
}
